### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by vrsanches** [vrsanches/bovespy#3]
- [ ] get stock list
- [ ] for each stock, get historical prices data
- [ ] implement Aroon Indicator
- [ ] implement reversal signal check
- [ ] check for consistent volume
- [ ] return final tendency
